# Generated by Django 4.2.5 on 2023-09-05 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_add_zip_to_Address'),
    ]

    operations = [
        migrations.RunSQL("""
            INSERT INTO store_collection(title)
            VALUES ('colletion1')
""","""
            DELETE FROM store_collection
            WHERE title= 'collection1'
"""
        )
    ]
