# Generated by Django 4.2.4 on 2023-08-30 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_add_zip_to_Address'),
    ]

    operations = [
        migrations.RunSQL(""" 
        INSERT INTO store_collection (title)
        VALUES ('collection1')
""", """ 
    DELETE FROM store_collection 
    WHERE title = 'collection1'
""")
    ]
