# Generated by Django 4.2.5 on 2023-10-06 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0002_alter_likeditems_object_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likeditems',
            name='object_id',
            field=models.PositiveIntegerField(),
        ),
    ]
